apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-static-check
spec:
  workspaces:
  - name: source
  steps:
    - name: static-check
      image: docker.io/golangci/golangci-lint:v1.27.0
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo Performing Static Check
        golangci-lint run --timeout=5m -v
