apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-unit-tests
spec:
  workspaces:
  - name: source
  steps:
    - name: download-dependencies
      image: docker.io/library/golang:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo Downloading dependencies
        go mod download
    - name: execute-tests
      image: docker.io/library/golang:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo Testing application
        go test -v
